// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANO7s01a8JcK04Xfm7cTfuBFAC07K3dCA',
    appId: '1:328007044956:web:9ff8fe7b46a7cddf0abb99',
    messagingSenderId: '328007044956',
    projectId: 'mychatapp-3226e',
    authDomain: 'mychatapp-3226e.firebaseapp.com',
    storageBucket: 'mychatapp-3226e.appspot.com',
    measurementId: 'G-2YFGXS71KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx4iiRTPjO4YXDwimUU7FafbwT8iM-Ev4',
    appId: '1:328007044956:android:19de3e07c168b9e60abb99',
    messagingSenderId: '328007044956',
    projectId: 'mychatapp-3226e',
    storageBucket: 'mychatapp-3226e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6n9MD5sZdD8EOTfVyKBEtqloK7eksNQ',
    appId: '1:328007044956:ios:109bb7c90bb7ce8b0abb99',
    messagingSenderId: '328007044956',
    projectId: 'mychatapp-3226e',
    storageBucket: 'mychatapp-3226e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK6n9MD5sZdD8EOTfVyKBEtqloK7eksNQ',
    appId: '1:328007044956:ios:109bb7c90bb7ce8b0abb99',
    messagingSenderId: '328007044956',
    projectId: 'mychatapp-3226e',
    storageBucket: 'mychatapp-3226e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANO7s01a8JcK04Xfm7cTfuBFAC07K3dCA',
    appId: '1:328007044956:web:6e28f8d8911d00540abb99',
    messagingSenderId: '328007044956',
    projectId: 'mychatapp-3226e',
    authDomain: 'mychatapp-3226e.firebaseapp.com',
    storageBucket: 'mychatapp-3226e.appspot.com',
    measurementId: 'G-ERL5VW1R45',
  );
}
